export default [
  // {
  //   id: 1,
  //   title: "User Management",
  //   router: "/user-management",
  //   dbTableName: "user",
  //   isEditable: true,
  //   data: [
  //     {
  //       id: 1,
  //       name: "",
  //       displayName: "Sr.No",
  //       order: 1,
  //       editable: true,
  //       displayOnTable: true,
  //       input: null,
  //     },
  //     {
  //       id: 2,
  //       name: "firstName",
  //       displayName: "First Name",
  //       order: 2,
  //       editable: true,
  //       displayOnTable: true,
  //       input: "text",
  //     },
  //     {
  //       id: 3,
  //       name: "lastName",
  //       displayName: "Last Name",
  //       order: 3,
  //       editable: true,
  //       displayOnTable: true,
  //       input: "text",
  //     },
  //     {
  //       id: 4,
  //       name: "",
  //       displayName: "Action",
  //       order: 4,
  //       editable: true,
  //       displayOnTable: true,
  //       input: "edit-delete",
  //     },
  //   ],
  // },
  {
    id: 1,
    title: "Plan Management",
    router: "/plan-management",
    dbTableName: "Plan",
    isEditable: true,
    apiURL: "plan",
    multiRecords: true,
    data: [
      {
        id: 1,
        name: "planTitle",
        displayName: "Plan Title",
        order: 1,
        editable: true,
        displayOnTable: true,
        input: "text",
        isActive: true,
        dataType: "String",
      },
      {
        id: 2,
        name: "planSubText",
        displayName: "Plan SubText",
        order: 2,
        editable: true,
        displayOnTable: true,
        input: "dropdown",
        isActive: true,
        dataType: "String",
        options: [
          { value: "", label: "Select" },
          { value: "option1", label: "Option 1" },
          { value: "option2", label: "Option 2" },
        ],
      },
      {
        id: 3,
        name: "planImage",
        displayName: "Plan Image",
        order: 3,
        editable: true,
        displayOnTable: true,
        input: "image",
        isActive: true,
        dataType: "String",
      },
      {
        id: 4,
        name: "planDescription",
        displayName: "Plan Description",
        order: 4,
        editable: true,
        displayOnTable: true,
        input: "textarea",
        isActive: true,
        dataType: "String",
      },
      {
        id: 5,
        name: "planCost",
        displayName: "Plan Cost",
        order: 5,
        editable: true,
        displayOnTable: true,
        input: "text",
        isActive: true,
        dataType: "String",
      },
      {
        id: 6,
        name: "availableInRural",
        displayName: "Available in Rural Area",
        order: 6,
        editable: true,
        displayOnTable: true,
        input: "radio",
        isActive: true,
        dataType: "String",
        options:['Yes','No']
      },
    ],
  },
  {
    id: 2,
    title: "Book Management",
    router: "/book-management",
    dbTableName: "book",
    isEditable: true,
    apiURL: "book",
    multiRecords: true,
    data: [
      {
        id: 1,
        name: "firstName",
        displayName: "Book Name",
        order: 1,
        editable: true,
        displayOnTable: true,
        input: "text",
        dataType: "String",
      },
      {
        id: 2,
        name: "lastName",
        displayName: "Book Price",
        order: 2,
        editable: true,
        displayOnTable: true,
        input: "text",
        dataType: "String",
      },
    ],
  },
  {
    id: 3,
    title: "Main Banner Text",
    router: "/main-banner-text-management",
    dbTableName: "BannerText",
    isEditable: true,
    apiURL: "banner",
    multiRecords: false,
    data: [
      {
        id: 1,
        name: "subHeading",
        displayName: "Sub Heading",
        order: 1,
        editable: true,
        displayOnTable: true,
        input: "text",
        dataType: "String",
        required: true,
      },
      {
        id: 2,
        name: "heading",
        displayName: "Heading",
        order: 2,
        editable: true,
        displayOnTable: true,
        input: "text",
        dataType: "String",
        required: true,
      },
      {
        id: 3,
        name: "description",
        displayName: "Description",
        order: 3,
        editable: true,
        displayOnTable: true,
        input: "text",
        dataType: "String",
        required: true,
      },
      {
        id: 4,
        name: "image",
        displayName: "Banner Image",
        order: 4,
        editable: true,
        displayOnTable: true,
        input: "image",
        dataType: "String",
        required: false,
      },
      {
        id: 5,
        name: "bannerimage",
        displayName: "Banner Logo",
        order: 5,
        editable: true,
        displayOnTable: true,
        input: "image",
        dataType: "String",
        required: false,
      },
    ],
  },
];
