export default [
    {
        formTitle:"Contact Us Form",
        dbTableName: "ContactUs",
        isEditable: true,
        apiURL: "contactus",
        multiRecords: true,
        returnUrl:'',
        successMessage:'',
        errorMessage:'',
        data:[
            {
                id: 1,
                name: "firstName",
                displayName: "First Name",
                order: 1,
                editable: true,
                displayOnTable: true,
                input: "text",
                isActive: true,
                dataType: "String",
                required: true,
              },
              {
                id: 2,
                name: "lastName",
                displayName: "Last Name",
                order: 2,
                editable: true,
                displayOnTable: true,
                input: "text",
                isActive: true,
                dataType: "String",
                required: true,
              },
              {
                id: 3,
                name: "email",
                displayName: "Email",
                order: 3,
                editable: true,
                displayOnTable: true,
                input: "text",
                isActive: true,
                dataType: "String",
                required: true,
              },
              {
                id: 4,
                name: "phone",
                displayName: "Phone",
                order: 4,
                editable: true,
                displayOnTable: true,
                input: "text",
                isActive: true,
                dataType: "String",
                required: true,
              },
              {
                id: 5,
                name: "message",
                displayName: "Message",
                order: 5,
                editable: true,
                displayOnTable: true,
                input: "textarea",
                isActive: true,
                dataType: "String",
                required: true,
              },
        ]
    }
]